export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  currency: string;
  imageUrl: string;
  productUrl: string;
  comfortScore: number; // 0 - 100
  styleScore: number; // 0 - 100
  durabilityScore: number; // 0 - 100
  description: string;
  category: string;
  features: string[];
  durabilityVerified: boolean;
  requiresAppOrSub: boolean;
  resaleHypeMarkup: boolean;
}

export const SNEAKER_CATALOG: Product[] = [
  {
    id: "nb-574-core",
    name: "New Balance 574 Core",
    brand: "New Balance",
    price: 89.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.newbalance.com",
    comfortScore: 86,
    styleScore: 84,
    durabilityScore: 88,
    description: "Classic suede and mesh heritage sneaker with ENCAP midsole cushioning for all-day support.",
    category: "Everyday / Heritage",
    features: ["ENCAP midsole", "Suede/mesh upper", "High traction outsole"],
    durabilityVerified: true,
    requiresAppOrSub: false,
    resaleHypeMarkup: false,
  },
  {
    id: "brooks-ghost-15",
    name: "Brooks Ghost 15 Cushion",
    brand: "Brooks",
    price: 109.95,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.brooksrunning.com",
    comfortScore: 95,
    styleScore: 74,
    durabilityScore: 92,
    description: "Plush DNA LOFT v2 cushioning built for runners and workers standing on their feet all day.",
    category: "Running / Max Cushion",
    features: ["DNA LOFT v2 cushioning", "Engineered air mesh", "Segmented Crash Pad"],
    durabilityVerified: true,
    requiresAppOrSub: false,
    resaleHypeMarkup: false,
  },
  {
    id: "adidas-stan-smith",
    name: "Adidas Originals Stan Smith",
    brand: "Adidas",
    price: 100.00,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.adidas.com",
    comfortScore: 78,
    styleScore: 92,
    durabilityScore: 85,
    description: "Iconic tennis silhouette with clean lines, smooth leather-look upper, and timeless aesthetic.",
    category: "Casual / Minimalist",
    features: ["Classic silhouette", "Recycled materials", "Rubber cupsole"],
    durabilityVerified: true,
    requiresAppOrSub: false,
    resaleHypeMarkup: false,
  },
  {
    id: "nike-air-max-sc",
    name: "Nike Air Max SC",
    brand: "Nike",
    price: 84.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.nike.com",
    comfortScore: 82,
    styleScore: 86,
    durabilityScore: 80,
    description: "Relaxed lines, heritage track look, and visible Max Air cushioning at an accessible price point.",
    category: "Lifestyle / Retro",
    features: ["Visible Max Air unit", "Leather & mesh", "Flex grooves"],
    durabilityVerified: true,
    requiresAppOrSub: false,
    resaleHypeMarkup: false,
  },
  {
    id: "asics-gel-nimbus-26",
    name: "Asics GEL-Nimbus 26",
    brand: "Asics",
    price: 149.00,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.asics.com",
    comfortScore: 97,
    styleScore: 80,
    durabilityScore: 89,
    description: "Engineered pureGEL cushioning and FF BLAST PLUS ECO foam right at the ceiling of your $150 budget.",
    category: "Max Comfort / Running",
    features: ["PureGEL technology", "Ortholite X-55 sockliner", "Hybrid ASICSGRIP outsole"],
    durabilityVerified: true,
    requiresAppOrSub: false,
    resaleHypeMarkup: false,
  },
  {
    id: "on-cloud-5",
    name: "On Cloud 5 All-Day",
    brand: "On Running",
    price: 139.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.on.com",
    comfortScore: 88,
    styleScore: 93,
    durabilityScore: 78,
    description: "Swiss-engineered ultralight shoe with signature CloudTec speed-lacing and sleek urban aesthetics.",
    category: "Lifestyle / Travel",
    features: ["CloudTec in Zero-Gravity foam", "Speed lacing", "Breathable antimicrobial mesh"],
    durabilityVerified: false,
    requiresAppOrSub: false,
    resaleHypeMarkup: false,
  },
  {
    id: "hoka-bondi-8",
    name: "Hoka Bondi 8 Ultra-Plush",
    brand: "Hoka",
    price: 165.00,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.hoka.com",
    comfortScore: 96,
    styleScore: 81,
    durabilityScore: 84,
    description: "One of the most cushioned shoes on the market, but priced above your hard budget constraint.",
    category: "Max Recovery / Walking",
    features: ["Engineered mesh", "Memory foam collar", "Rear crash pad"],
    durabilityVerified: true,
    requiresAppOrSub: false,
    resaleHypeMarkup: false,
  },
  {
    id: "nike-air-jordan-4-retro",
    name: "Nike Air Jordan 4 Retro 'Bred'",
    brand: "Nike",
    price: 215.00,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.nike.com",
    comfortScore: 71,
    styleScore: 98,
    durabilityScore: 86,
    description: "High-hype sneaker heavily promoted by algorithms and platforms, despite exceeding your budget by $65.",
    category: "Hype / Streetwear",
    features: ["Visible Air-Sole unit", "Sculpted midsole", "Heritage basketball design"],
    durabilityVerified: true,
    requiresAppOrSub: false,
    resaleHypeMarkup: true,
  },
  {
    id: "balenciaga-triple-s",
    name: "Balenciaga Triple S Clear Sole",
    brand: "Balenciaga",
    price: 1050.00,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.balenciaga.com",
    comfortScore: 62,
    styleScore: 91,
    durabilityScore: 75,
    description: "Luxury oversized trainer aggressively pushed by high-margin affiliate networks.",
    category: "Luxury Fashion",
    features: ["Complex 3-layered outsole", "Embroidered logo"],
    durabilityVerified: false,
    requiresAppOrSub: false,
    resaleHypeMarkup: true,
  },
];

